# Generated by Django 6.0.3 on 2026-03-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age_user_bio_user_gender_user_looking_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='Есть видео'),
        ),
    ]
