# Generated by Django 6.0.3 on 2026-03-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram @username'),
        ),
    ]
